-- SIEM Africa - Module 2 : MITRE ATT&CK seed data
-- 14 tactics + MITRE techniques + 380 detection signatures
-- Source: MITRE ATT&CK Enterprise v15 (https://attack.mitre.org/)

BEGIN TRANSACTION;

-- ============================================================
-- 14 TACTICS
-- ============================================================
INSERT OR REPLACE INTO mitre_tactics (id, name, description, url) VALUES
 ('TA0043', 'Reconnaissance',            'Gathering information to plan future operations',                          'https://attack.mitre.org/tactics/TA0043/'),
 ('TA0042', 'Resource Development',      'Establishing resources used to support operations',                        'https://attack.mitre.org/tactics/TA0042/'),
 ('TA0001', 'Initial Access',            'Gaining an initial foothold on a network',                                 'https://attack.mitre.org/tactics/TA0001/'),
 ('TA0002', 'Execution',                 'Running malicious code on a local or remote system',                       'https://attack.mitre.org/tactics/TA0002/'),
 ('TA0003', 'Persistence',               'Maintaining access across restarts, credential changes, or interruptions', 'https://attack.mitre.org/tactics/TA0003/'),
 ('TA0004', 'Privilege Escalation',      'Gaining higher-level permissions',                                         'https://attack.mitre.org/tactics/TA0004/'),
 ('TA0005', 'Defense Evasion',           'Avoiding detection by defenders',                                          'https://attack.mitre.org/tactics/TA0005/'),
 ('TA0006', 'Credential Access',         'Stealing credentials',                                                     'https://attack.mitre.org/tactics/TA0006/'),
 ('TA0007', 'Discovery',                 'Exploring the environment',                                                'https://attack.mitre.org/tactics/TA0007/'),
 ('TA0008', 'Lateral Movement',          'Moving through the environment',                                           'https://attack.mitre.org/tactics/TA0008/'),
 ('TA0009', 'Collection',                'Gathering data of interest',                                               'https://attack.mitre.org/tactics/TA0009/'),
 ('TA0011', 'Command and Control',       'Communicating with compromised systems',                                   'https://attack.mitre.org/tactics/TA0011/'),
 ('TA0010', 'Exfiltration',              'Stealing data',                                                            'https://attack.mitre.org/tactics/TA0010/'),
 ('TA0040', 'Impact',                    'Disrupting, destroying or manipulating systems and data',                  'https://attack.mitre.org/tactics/TA0040/');

-- ============================================================
-- TECHNIQUES (and sub-techniques) used by the 380 signatures
-- ============================================================
INSERT OR REPLACE INTO mitre_techniques (id, tactic_id, parent_id, name, description, url) VALUES
 -- Reconnaissance
 ('T1595',        'TA0043', NULL,     'Active Scanning',                  'Active probes of victim infrastructure',     'https://attack.mitre.org/techniques/T1595/'),
 ('T1595.001',    'TA0043', 'T1595',  'Scanning IP Blocks',               'Network sweeps to enumerate live hosts',    'https://attack.mitre.org/techniques/T1595/001/'),
 ('T1595.002',    'TA0043', 'T1595',  'Vulnerability Scanning',           'Probes for known vulnerabilities',           'https://attack.mitre.org/techniques/T1595/002/'),
 ('T1595.003',    'TA0043', 'T1595',  'Wordlist Scanning',                'Brute-force discovery with wordlists',       'https://attack.mitre.org/techniques/T1595/003/'),
 ('T1589',        'TA0043', NULL,     'Gather Victim Identity Information','Collect user / account information',        'https://attack.mitre.org/techniques/T1589/'),
 ('T1590',        'TA0043', NULL,     'Gather Victim Network Information','DNS, WHOIS, routing topology',              'https://attack.mitre.org/techniques/T1590/'),
 ('T1592',        'TA0043', NULL,     'Gather Victim Host Information',   'Hardware, software, firmware information',    'https://attack.mitre.org/techniques/T1592/'),
 -- Initial Access
 ('T1190',        'TA0001', NULL,     'Exploit Public-Facing Application','Exploit internet-facing services',           'https://attack.mitre.org/techniques/T1190/'),
 ('T1133',        'TA0001', NULL,     'External Remote Services',         'Abuse external remote services',             'https://attack.mitre.org/techniques/T1133/'),
 ('T1566',        'TA0001', NULL,     'Phishing',                         'Electronically delivered social engineering','https://attack.mitre.org/techniques/T1566/'),
 ('T1566.001',    'TA0001', 'T1566',  'Spearphishing Attachment',         'Malicious file attachment',                  'https://attack.mitre.org/techniques/T1566/001/'),
 ('T1566.002',    'TA0001', 'T1566',  'Spearphishing Link',               'Malicious link in email',                    'https://attack.mitre.org/techniques/T1566/002/'),
 ('T1078',        'TA0001', NULL,     'Valid Accounts',                   'Use of legitimate credentials',              'https://attack.mitre.org/techniques/T1078/'),
 ('T1078.001',    'TA0001', 'T1078',  'Default Accounts',                 'Use vendor-default accounts',                'https://attack.mitre.org/techniques/T1078/001/'),
 ('T1078.002',    'TA0001', 'T1078',  'Domain Accounts',                  'Use of AD domain account',                   'https://attack.mitre.org/techniques/T1078/002/'),
 ('T1078.003',    'TA0001', 'T1078',  'Local Accounts',                   'Use of local system account',                'https://attack.mitre.org/techniques/T1078/003/'),
 ('T1195',        'TA0001', NULL,     'Supply Chain Compromise',          'Compromise via supplier / dependency',       'https://attack.mitre.org/techniques/T1195/'),
 ('T1199',        'TA0001', NULL,     'Trusted Relationship',             'Abuse of 3rd-party trust',                   'https://attack.mitre.org/techniques/T1199/'),
 -- Execution
 ('T1059',        'TA0002', NULL,     'Command and Scripting Interpreter','Use shells and scripting interpreters',      'https://attack.mitre.org/techniques/T1059/'),
 ('T1059.001',    'TA0002', 'T1059',  'PowerShell',                       'PowerShell abuse',                           'https://attack.mitre.org/techniques/T1059/001/'),
 ('T1059.003',    'TA0002', 'T1059',  'Windows Command Shell',            'cmd.exe abuse',                              'https://attack.mitre.org/techniques/T1059/003/'),
 ('T1059.004',    'TA0002', 'T1059',  'Unix Shell',                       'bash / sh abuse',                            'https://attack.mitre.org/techniques/T1059/004/'),
 ('T1059.006',    'TA0002', 'T1059',  'Python',                           'Malicious Python execution',                 'https://attack.mitre.org/techniques/T1059/006/'),
 ('T1059.007',    'TA0002', 'T1059',  'JavaScript',                       'Malicious JS execution',                     'https://attack.mitre.org/techniques/T1059/007/'),
 ('T1203',        'TA0002', NULL,     'Exploitation for Client Execution','Exploit client-side vulnerabilities',        'https://attack.mitre.org/techniques/T1203/'),
 ('T1053',        'TA0002', NULL,     'Scheduled Task/Job',               'Use scheduler to execute code',              'https://attack.mitre.org/techniques/T1053/'),
 ('T1053.003',    'TA0002', 'T1053',  'Cron',                             'Linux cron abuse',                           'https://attack.mitre.org/techniques/T1053/003/'),
 ('T1053.005',    'TA0002', 'T1053',  'Scheduled Task',                   'Windows schtasks abuse',                     'https://attack.mitre.org/techniques/T1053/005/'),
 ('T1047',        'TA0002', NULL,     'Windows Management Instrumentation','WMI abuse',                                  'https://attack.mitre.org/techniques/T1047/'),
 -- Persistence
 ('T1098',        'TA0003', NULL,     'Account Manipulation',             'Modify existing accounts',                   'https://attack.mitre.org/techniques/T1098/'),
 ('T1136',        'TA0003', NULL,     'Create Account',                   'Create local / cloud / domain account',      'https://attack.mitre.org/techniques/T1136/'),
 ('T1543',        'TA0003', NULL,     'Create or Modify System Process',  'Install malicious service / daemon',         'https://attack.mitre.org/techniques/T1543/'),
 ('T1543.002',    'TA0003', 'T1543',  'Systemd Service',                  'Linux systemd service persistence',          'https://attack.mitre.org/techniques/T1543/002/'),
 ('T1547',        'TA0003', NULL,     'Boot or Logon Autostart Execution','Autostart via boot / logon hooks',           'https://attack.mitre.org/techniques/T1547/'),
 ('T1505',        'TA0003', NULL,     'Server Software Component',        'Web shell or other server module',           'https://attack.mitre.org/techniques/T1505/'),
 ('T1505.003',    'TA0003', 'T1505',  'Web Shell',                        'PHP/JSP/ASPX web shell',                     'https://attack.mitre.org/techniques/T1505/003/'),
 ('T1037',        'TA0003', NULL,     'Boot or Logon Initialization Scripts','Login script abuse',                      'https://attack.mitre.org/techniques/T1037/'),
 ('T1546',        'TA0003', NULL,     'Event Triggered Execution',        'Trigger code on system events',              'https://attack.mitre.org/techniques/T1546/'),
 -- Privilege Escalation
 ('T1548',        'TA0004', NULL,     'Abuse Elevation Control Mechanism','UAC / sudo abuse',                           'https://attack.mitre.org/techniques/T1548/'),
 ('T1548.001',    'TA0004', 'T1548',  'Setuid and Setgid',                'Abuse setuid/setgid binaries',               'https://attack.mitre.org/techniques/T1548/001/'),
 ('T1548.003',    'TA0004', 'T1548',  'Sudo and Sudo Caching',            'Abuse sudo',                                 'https://attack.mitre.org/techniques/T1548/003/'),
 ('T1068',        'TA0004', NULL,     'Exploitation for Privilege Escalation','Kernel / local root exploits',           'https://attack.mitre.org/techniques/T1068/'),
 ('T1134',        'TA0004', NULL,     'Access Token Manipulation',        'Impersonate or manipulate tokens',           'https://attack.mitre.org/techniques/T1134/'),
 -- Defense Evasion
 ('T1070',        'TA0005', NULL,     'Indicator Removal',                'Remove evidence of activity',                'https://attack.mitre.org/techniques/T1070/'),
 ('T1070.002',    'TA0005', 'T1070',  'Clear Linux or Mac System Logs',   'Wipe /var/log',                               'https://attack.mitre.org/techniques/T1070/002/'),
 ('T1070.004',    'TA0005', 'T1070',  'File Deletion',                    'Delete files to remove evidence',            'https://attack.mitre.org/techniques/T1070/004/'),
 ('T1027',        'TA0005', NULL,     'Obfuscated Files or Information',  'Encode/obfuscate payloads',                  'https://attack.mitre.org/techniques/T1027/'),
 ('T1562',        'TA0005', NULL,     'Impair Defenses',                  'Disable security tools',                     'https://attack.mitre.org/techniques/T1562/'),
 ('T1562.001',    'TA0005', 'T1562',  'Disable or Modify Tools',          'Kill AV / EDR',                               'https://attack.mitre.org/techniques/T1562/001/'),
 ('T1562.004',    'TA0005', 'T1562',  'Disable or Modify System Firewall','iptables / firewalld changes',               'https://attack.mitre.org/techniques/T1562/004/'),
 ('T1055',        'TA0005', NULL,     'Process Injection',                'Inject into running processes',              'https://attack.mitre.org/techniques/T1055/'),
 -- Credential Access
 ('T1110',        'TA0006', NULL,     'Brute Force',                      'Systematic authentication guessing',         'https://attack.mitre.org/techniques/T1110/'),
 ('T1110.001',    'TA0006', 'T1110',  'Password Guessing',                'Repeated password attempts',                 'https://attack.mitre.org/techniques/T1110/001/'),
 ('T1110.002',    'TA0006', 'T1110',  'Password Cracking',                'Offline cracking of hashes',                 'https://attack.mitre.org/techniques/T1110/002/'),
 ('T1110.003',    'TA0006', 'T1110',  'Password Spraying',                'One password across many accounts',          'https://attack.mitre.org/techniques/T1110/003/'),
 ('T1110.004',    'TA0006', 'T1110',  'Credential Stuffing',              'Re-use of leaked credentials',               'https://attack.mitre.org/techniques/T1110/004/'),
 ('T1003',        'TA0006', NULL,     'OS Credential Dumping',            'Dump credentials from OS',                   'https://attack.mitre.org/techniques/T1003/'),
 ('T1003.001',    'TA0006', 'T1003',  'LSASS Memory',                     'Dump lsass.exe memory',                      'https://attack.mitre.org/techniques/T1003/001/'),
 ('T1003.008',    'TA0006', 'T1003',  '/etc/passwd and /etc/shadow',      'Dump Linux password / shadow files',         'https://attack.mitre.org/techniques/T1003/008/'),
 ('T1552',        'TA0006', NULL,     'Unsecured Credentials',            'Find creds in files / env / registry',       'https://attack.mitre.org/techniques/T1552/'),
 ('T1552.001',    'TA0006', 'T1552',  'Credentials In Files',             'Search for creds in config files',           'https://attack.mitre.org/techniques/T1552/001/'),
 ('T1040',        'TA0006', NULL,     'Network Sniffing',                 'Capture network traffic',                    'https://attack.mitre.org/techniques/T1040/'),
 ('T1556',        'TA0006', NULL,     'Modify Authentication Process',    'Tamper with auth mechanisms',                 'https://attack.mitre.org/techniques/T1556/'),
 -- Discovery
 ('T1046',        'TA0007', NULL,     'Network Service Discovery',        'Enumerate services / ports',                 'https://attack.mitre.org/techniques/T1046/'),
 ('T1018',        'TA0007', NULL,     'Remote System Discovery',          'Enumerate systems on the network',            'https://attack.mitre.org/techniques/T1018/'),
 ('T1083',        'TA0007', NULL,     'File and Directory Discovery',     'Enumerate files / directories',              'https://attack.mitre.org/techniques/T1083/'),
 ('T1087',        'TA0007', NULL,     'Account Discovery',                'Enumerate user accounts',                    'https://attack.mitre.org/techniques/T1087/'),
 ('T1082',        'TA0007', NULL,     'System Information Discovery',     'Enumerate system information',               'https://attack.mitre.org/techniques/T1082/'),
 ('T1135',        'TA0007', NULL,     'Network Share Discovery',          'Enumerate SMB / NFS shares',                 'https://attack.mitre.org/techniques/T1135/'),
 ('T1016',        'TA0007', NULL,     'System Network Configuration Discovery','Enumerate IP / DNS config',             'https://attack.mitre.org/techniques/T1016/'),
 ('T1057',        'TA0007', NULL,     'Process Discovery',                'List running processes',                     'https://attack.mitre.org/techniques/T1057/'),
 -- Lateral Movement
 ('T1021',        'TA0008', NULL,     'Remote Services',                  'Remote service abuse (RDP/SSH/SMB)',         'https://attack.mitre.org/techniques/T1021/'),
 ('T1021.001',    'TA0008', 'T1021',  'Remote Desktop Protocol',          'RDP lateral movement',                       'https://attack.mitre.org/techniques/T1021/001/'),
 ('T1021.002',    'TA0008', 'T1021',  'SMB/Windows Admin Shares',         'SMB lateral movement',                       'https://attack.mitre.org/techniques/T1021/002/'),
 ('T1021.004',    'TA0008', 'T1021',  'SSH',                              'SSH lateral movement',                       'https://attack.mitre.org/techniques/T1021/004/'),
 ('T1080',        'TA0008', NULL,     'Taint Shared Content',             'Modify files on shared content',              'https://attack.mitre.org/techniques/T1080/'),
 ('T1570',        'TA0008', NULL,     'Lateral Tool Transfer',            'Copy tools across systems',                  'https://attack.mitre.org/techniques/T1570/'),
 -- Collection
 ('T1005',        'TA0009', NULL,     'Data from Local System',           'Collect local files',                        'https://attack.mitre.org/techniques/T1005/'),
 ('T1039',        'TA0009', NULL,     'Data from Network Shared Drive',   'Collect files from shares',                  'https://attack.mitre.org/techniques/T1039/'),
 ('T1560',        'TA0009', NULL,     'Archive Collected Data',           'Compress / encrypt data for exfil',           'https://attack.mitre.org/techniques/T1560/'),
 ('T1113',        'TA0009', NULL,     'Screen Capture',                   'Capture user screens',                       'https://attack.mitre.org/techniques/T1113/'),
 -- Command and Control
 ('T1071',        'TA0011', NULL,     'Application Layer Protocol',       'Use app-layer protocols for C2',             'https://attack.mitre.org/techniques/T1071/'),
 ('T1071.001',    'TA0011', 'T1071',  'Web Protocols',                    'HTTP/S for C2',                              'https://attack.mitre.org/techniques/T1071/001/'),
 ('T1071.002',    'TA0011', 'T1071',  'File Transfer Protocols',          'FTP / SFTP for C2',                          'https://attack.mitre.org/techniques/T1071/002/'),
 ('T1071.004',    'TA0011', 'T1071',  'DNS',                              'DNS tunneling / beaconing',                  'https://attack.mitre.org/techniques/T1071/004/'),
 ('T1090',        'TA0011', NULL,     'Proxy',                            'Use proxies to hide origin',                 'https://attack.mitre.org/techniques/T1090/'),
 ('T1095',        'TA0011', NULL,     'Non-Application Layer Protocol',   'Raw TCP/UDP/ICMP for C2',                    'https://attack.mitre.org/techniques/T1095/'),
 ('T1571',        'TA0011', NULL,     'Non-Standard Port',                'Use uncommon ports for known protocols',      'https://attack.mitre.org/techniques/T1571/'),
 ('T1105',        'TA0011', NULL,     'Ingress Tool Transfer',            'Download tools to victim',                   'https://attack.mitre.org/techniques/T1105/'),
 ('T1572',        'TA0011', NULL,     'Protocol Tunneling',               'Tunnel protocols inside others',             'https://attack.mitre.org/techniques/T1572/'),
 ('T1573',        'TA0011', NULL,     'Encrypted Channel',                'Custom / standard crypto for C2',            'https://attack.mitre.org/techniques/T1573/'),
 -- Exfiltration
 ('T1041',        'TA0010', NULL,     'Exfiltration Over C2 Channel',     'Steal data via C2 channel',                  'https://attack.mitre.org/techniques/T1041/'),
 ('T1048',        'TA0010', NULL,     'Exfiltration Over Alternative Protocol','Use alt protocol for exfil',           'https://attack.mitre.org/techniques/T1048/'),
 ('T1567',        'TA0010', NULL,     'Exfiltration Over Web Service',    'Use cloud / public web service',             'https://attack.mitre.org/techniques/T1567/'),
 ('T1029',        'TA0010', NULL,     'Scheduled Transfer',               'Schedule exfil to blend in',                 'https://attack.mitre.org/techniques/T1029/'),
 -- Impact
 ('T1486',        'TA0040', NULL,     'Data Encrypted for Impact',        'Ransomware encryption',                      'https://attack.mitre.org/techniques/T1486/'),
 ('T1485',        'TA0040', NULL,     'Data Destruction',                 'Destroy data / wipers',                      'https://attack.mitre.org/techniques/T1485/'),
 ('T1496',        'TA0040', NULL,     'Resource Hijacking',               'Crypto mining / steal resources',            'https://attack.mitre.org/techniques/T1496/'),
 ('T1499',        'TA0040', NULL,     'Endpoint Denial of Service',       'Crash endpoint services',                    'https://attack.mitre.org/techniques/T1499/'),
 ('T1498',        'TA0040', NULL,     'Network Denial of Service',        'Flood network with traffic',                 'https://attack.mitre.org/techniques/T1498/'),
 ('T1565',        'TA0040', NULL,     'Data Manipulation',                'Tamper with data at rest / in transit',      'https://attack.mitre.org/techniques/T1565/'),
 ('T1491',        'TA0040', NULL,     'Defacement',                       'Deface websites / systems',                  'https://attack.mitre.org/techniques/T1491/');

-- ============================================================
-- 380 DETECTION SIGNATURES
--
-- Fields: (id, technique_id, name, description, severity, keywords, fp_likelihood)
-- Severity : 1..10 (10 = critical)
-- fp_likelihood : 0..1 (probability this signature is a false positive)
-- keywords : pipe-separated tokens matched against alert rule description / payload
-- ============================================================

-- --- Block 1 : Reconnaissance & scanning (SIG-001..040) ---------
INSERT OR REPLACE INTO signatures (id, technique_id, name, description, severity, keywords, fp_likelihood) VALUES
 ('SIG-001','T1595.001','TCP SYN scan',                'Rapid SYN packets to multiple ports from one source',                    5,'syn_scan|nmap|masscan|stealth scan',               0.30),
 ('SIG-002','T1595.001','TCP connect scan',            'Full TCP handshake scan',                                                4,'connect scan|nmap -sT|tcp scan',                    0.30),
 ('SIG-003','T1595.001','TCP FIN scan',                'FIN flag probe (RFC 793 trick)',                                          5,'fin scan|nmap -sF',                                 0.25),
 ('SIG-004','T1595.001','TCP NULL scan',               'No-flag TCP packet probe',                                                5,'null scan|nmap -sN',                                0.25),
 ('SIG-005','T1595.001','TCP Xmas scan',               'FIN+PSH+URG probe',                                                       5,'xmas scan|nmap -sX',                                0.25),
 ('SIG-006','T1595.001','UDP scan',                    'UDP port scan',                                                           4,'udp scan|nmap -sU',                                 0.35),
 ('SIG-007','T1595.001','ICMP ping sweep',             'Ping to many hosts on subnet',                                            3,'ping sweep|icmp echo|nmap -sn',                     0.45),
 ('SIG-008','T1595.001','ARP sweep',                   'Large ARP scan on local network',                                         3,'arp scan|arp-scan|netdiscover',                     0.40),
 ('SIG-009','T1595.002','Nessus vulnerability scan',   'Nessus user-agent or plugin fingerprint',                                 5,'Nessus|NessusScan|tenable',                         0.20),
 ('SIG-010','T1595.002','OpenVAS vulnerability scan',  'OpenVAS / Greenbone scanning footprint',                                  5,'OpenVAS|greenbone|gvm',                             0.20),
 ('SIG-011','T1595.002','Nikto web scan',              'Nikto user-agent',                                                        5,'Nikto|mozilla/4.75 (Nikto)',                        0.15),
 ('SIG-012','T1595.002','Wapiti web scan',             'Wapiti user-agent',                                                       4,'Wapiti|wapiti/',                                    0.20),
 ('SIG-013','T1595.003','Dirbuster content discovery', 'Dirbuster / dirb brute-force of paths',                                   4,'DirBuster|dirb|gobuster|ffuf',                      0.20),
 ('SIG-014','T1595.003','Wordlist HTTP probing',       'Large number of 404s to common paths',                                    4,'/admin|/wp-admin|/phpmyadmin|/backup|/.git',        0.25),
 ('SIG-015','T1595.001','Zmap fast scanner',           'Zmap internet-scale scanner',                                             6,'zmap|zgrab',                                        0.15),
 ('SIG-016','T1595.001','Shodan crawler probe',        'Shodan banner grab',                                                      3,'shodan.io|census|project-resonance',                0.55),
 ('SIG-017','T1595.002','Metasploit auxiliary scan',   'Metasploit scanner module activity',                                      7,'msf auxiliary|metasploit',                          0.15),
 ('SIG-018','T1595.001','Slow scan (T2 timing)',       'Very low-rate scan to evade detection',                                   4,'slow scan|timing=paranoid|nmap -T0',                0.40),
 ('SIG-019','T1589',    'LDAP enumeration',            'Anonymous or null-bind LDAP query',                                       5,'ldap anonymous|nullbind|ldapsearch',                0.35),
 ('SIG-020','T1589',    'SMTP VRFY/EXPN enumeration',  'Mail user enumeration via VRFY/EXPN',                                     4,'VRFY|EXPN|SMTP enumeration',                        0.30),
 ('SIG-021','T1590',    'DNS zone transfer attempt',   'AXFR request to DNS server',                                              6,'AXFR|zone transfer|dig axfr',                       0.20),
 ('SIG-022','T1590',    'Reverse DNS sweep',           'Bulk PTR queries for a subnet',                                           3,'ptr lookup|reverse dns sweep',                      0.50),
 ('SIG-023','T1592',    'OS fingerprint (TCP/IP stack)','nmap -O / xprobe fingerprinting',                                        4,'os fingerprint|nmap -O|xprobe',                     0.30),
 ('SIG-024','T1592',    'Banner grabbing',             'Service banner harvesting',                                               3,'banner grab|nc -nv|telnet banner',                  0.50),
 ('SIG-025','T1595.002','Qualys scanner detected',     'Qualys enterprise scanner',                                               3,'Qualys|qualysguard',                                0.55),
 ('SIG-026','T1595.002','Acunetix web scan',           'Acunetix web vulnerability scanner',                                      5,'acunetix|acunetix-aspect',                          0.15),
 ('SIG-027','T1595.002','Burp Suite scan',             'Burp Suite active scan',                                                  4,'Burp Suite|burpcollaborator',                       0.25),
 ('SIG-028','T1595.002','ZAP web scan',                'OWASP ZAP active scan',                                                   4,'OWASP ZAP|ZAP/|zaproxy',                            0.25),
 ('SIG-029','T1595.002','SQLMap scan',                 'SQLMap SQL injection scanner',                                            8,'sqlmap|sqlmap/',                                    0.10),
 ('SIG-030','T1595.002','WPScan WordPress scan',       'WPScan WordPress vulnerability scanner',                                  5,'WPScan|wpscan/',                                    0.20),
 ('SIG-031','T1046',    'Port scan high count',        'More than 100 ports probed by one IP in 60 s',                            6,'port scan|high port count',                         0.20),
 ('SIG-032','T1046',    'SSH port probe',              'Probe of SSH ports 22 / 2222',                                            4,'ssh probe|port 22',                                 0.50),
 ('SIG-033','T1046',    'RDP port probe',              'Probe of RDP port 3389',                                                  5,'rdp probe|port 3389',                               0.35),
 ('SIG-034','T1046',    'SMB port probe',              'Probe of SMB ports 139 / 445',                                            5,'smb probe|port 445|port 139',                       0.35),
 ('SIG-035','T1046',    'Database port probe',         'Probe of MySQL / Postgres / MSSQL / MongoDB ports',                       6,'port 3306|port 5432|port 1433|port 27017',          0.30),
 ('SIG-036','T1046',    'ICS/SCADA port probe',        'Probe of Modbus / DNP3 / S7 ports',                                       8,'port 502|modbus|port 44818|ethernet/ip',            0.20),
 ('SIG-037','T1046',    'Telnet probe',                'Telnet service probe (plaintext legacy)',                                 4,'telnet|port 23',                                    0.45),
 ('SIG-038','T1046',    'VNC probe',                   'VNC service probe',                                                       5,'vnc|port 5900|rfb',                                 0.35),
 ('SIG-039','T1595.001','Aggressive ping flood',       'Thousands of ICMP echo per minute',                                       5,'ping flood|icmp flood',                             0.30),
 ('SIG-040','T1595.001','SNMP community sweep',        'Brute-force of SNMP community strings',                                   5,'snmp community|snmpwalk|public community',          0.30);

-- --- Block 2 : Brute force & credential attacks (SIG-041..080) ---
INSERT OR REPLACE INTO signatures (id, technique_id, name, description, severity, keywords, fp_likelihood) VALUES
 ('SIG-041','T1110.001','SSH password brute force',            'Repeated SSH password failures from same source',                 7,'sshd: Failed password|authentication failure ssh', 0.15),
 ('SIG-042','T1110.003','SSH password spraying',               'One password tried against many users via SSH',                   8,'sshd: Failed password|multiple users',             0.15),
 ('SIG-043','T1110.001','FTP brute force',                     'Repeated FTP login failures',                                     6,'FTP login failure|530 Login incorrect',             0.20),
 ('SIG-044','T1110.001','IMAP brute force',                    'Repeated IMAP login failures',                                    6,'imap login failure|LOGIN failed',                   0.20),
 ('SIG-045','T1110.001','POP3 brute force',                    'Repeated POP3 login failures',                                    6,'pop3 login failure|-ERR',                           0.20),
 ('SIG-046','T1110.001','SMTP AUTH brute force',               'Repeated SMTP AUTH failures',                                     6,'SMTP AUTH failure|535 Authentication',              0.20),
 ('SIG-047','T1110.001','MySQL brute force',                   'Repeated MySQL login failures',                                   7,'mysql access denied|ER_ACCESS_DENIED_ERROR',        0.15),
 ('SIG-048','T1110.001','Postgres brute force',                'Repeated PostgreSQL login failures',                              7,'postgres FATAL: password authentication',           0.15),
 ('SIG-049','T1110.001','MSSQL brute force',                   'Repeated MSSQL login failures',                                   7,'login failed for user|mssql login',                 0.15),
 ('SIG-050','T1110.001','RDP brute force',                     'Repeated RDP login failures',                                     8,'rdp login failure|4625|logon type 10',              0.10),
 ('SIG-051','T1110.001','VNC brute force',                     'Repeated VNC authentication failures',                            6,'vnc auth failed|authentication failure vnc',        0.20),
 ('SIG-052','T1110.001','Telnet brute force',                  'Repeated telnet login failures',                                  6,'telnet login failed|login incorrect',               0.20),
 ('SIG-053','T1110.001','Web form brute force',                'Repeated HTTP 401 / 403 to login endpoints',                      6,'login failed|401|invalid credentials',              0.25),
 ('SIG-054','T1110.004','Credential stuffing (known list)',    'Known breached credentials combination',                          8,'credential stuffing|leaked credentials',            0.10),
 ('SIG-055','T1110.003','ADFS password spraying',              'Microsoft ADFS password spraying attempt',                        8,'adfs|azure ad spray',                               0.10),
 ('SIG-056','T1110.001','WordPress wp-login brute force',      'Repeated wp-login.php POST failures',                             7,'wp-login.php|wordpress bruteforce',                 0.15),
 ('SIG-057','T1110.001','Joomla admin brute force',            'Joomla /administrator brute force',                               7,'joomla administrator|com_login',                    0.15),
 ('SIG-058','T1110.001','Drupal user login brute force',       'Drupal /user/login brute force',                                  6,'drupal /user/login|invalid username',               0.20),
 ('SIG-059','T1110.001','phpMyAdmin brute force',              'Repeated phpMyAdmin login failures',                              7,'phpmyadmin|index.php?route=login',                  0.15),
 ('SIG-060','T1110.001','Cisco SSH brute force',               'Cisco device SSH brute force',                                    8,'cisco authentication failure|vty',                  0.10),
 ('SIG-061','T1110.002','Hashcat / John the Ripper pattern',   'Offline hash cracking indicators',                                3,'hashcat|john the ripper',                           0.30),
 ('SIG-062','T1003.001','Mimikatz signature',                  'Mimikatz credential dumper indicator',                           10,'mimikatz|sekurlsa::logonpasswords',                 0.05),
 ('SIG-063','T1003.001','LSASS access attempt',                'Suspicious process reads lsass.exe memory',                       9,'lsass.exe|OpenProcess lsass',                       0.10),
 ('SIG-064','T1003.008','/etc/shadow read attempt',            'Non-root read of /etc/shadow',                                    9,'read /etc/shadow|cat /etc/shadow',                  0.15),
 ('SIG-065','T1003.008','passwd file exfil attempt',           'Read of /etc/passwd by web process',                              7,'/etc/passwd|../../../etc/passwd',                   0.15),
 ('SIG-066','T1552.001','AWS credentials file accessed',       'Read of .aws/credentials',                                        8,'.aws/credentials|AKIA',                             0.15),
 ('SIG-067','T1552.001','SSH private key access',              'Read of id_rsa / id_ed25519',                                     7,'id_rsa|id_ed25519|.ssh/',                           0.20),
 ('SIG-068','T1552.001','Grep for password in source',         'Process greps for "password=" in /etc or /home',                  5,'grep -r password|pass=|password=',                  0.30),
 ('SIG-069','T1552.001','Kubernetes kubeconfig access',        'Read of ~/.kube/config',                                          6,'.kube/config|kubectl',                              0.25),
 ('SIG-070','T1552.001','Database URL with password leaked',   'DB URL with plaintext creds in logs',                             6,'postgres://|mysql://|mongodb://',                   0.35),
 ('SIG-071','T1040',    'Tcpdump / tshark running',            'Packet capture tool invocation',                                  5,'tcpdump|tshark|wireshark',                          0.40),
 ('SIG-072','T1040',    'ARP spoofing detected',               'ARP cache manipulation on LAN',                                   8,'arp spoof|arp poisoning|ettercap',                  0.15),
 ('SIG-073','T1556',    'PAM module modification',             'PAM config changed at runtime',                                   8,'/etc/pam.d|pam_unix.so modified',                   0.15),
 ('SIG-074','T1556',    'Skeleton key AD modification',        'AD skeleton key pattern',                                         9,'skeleton key|kerberos',                             0.10),
 ('SIG-075','T1003',    'procdump.exe against lsass',          'Sysinternals procdump targeting lsass',                          10,'procdump|procdump -ma lsass',                       0.05),
 ('SIG-076','T1003',    'Shadow Copy volume dump',              'vssadmin create shadow + dump',                                  8,'vssadmin|create shadow',                            0.15),
 ('SIG-077','T1003',    'Registry hive SAM export',             'reg save HKLM\\SAM',                                              8,'reg save|HKLM\\SAM',                                0.15),
 ('SIG-078','T1110.001','Kerberos AS-REP roasting',            'AS-REP requests for accounts w/o preauth',                        8,'AS-REP|kerberoast|preauth',                         0.10),
 ('SIG-079','T1110.002','Kerberoasting detected',              'SPN requests followed by hash cracking pattern',                  8,'kerberoast|TGS-REQ|SPN',                            0.10),
 ('SIG-080','T1110.003','O365 password spraying',              'Password spraying against Office 365',                            8,'o365|aadsts50126|azure spray',                      0.10);

-- --- Block 3 : Web attacks (SIG-081..140) -----------------------
INSERT OR REPLACE INTO signatures (id, technique_id, name, description, severity, keywords, fp_likelihood) VALUES
 ('SIG-081','T1190','SQL injection UNION SELECT',              'UNION SELECT pattern in HTTP request',                            8,'UNION SELECT|union all select|sql injection',       0.10),
 ('SIG-082','T1190','SQL injection OR 1=1',                    'Classic OR 1=1 bypass',                                           8,'or 1=1|'' or ''1''=''1|admin''--',                  0.10),
 ('SIG-083','T1190','SQL injection sleep / benchmark',         'Time-based blind SQLi',                                           8,'sleep(|benchmark(|waitfor delay',                   0.10),
 ('SIG-084','T1190','SQL injection error-based',               'SQL syntax error leaked via HTTP response',                       7,'sql syntax error|mysql_fetch|ora-',                 0.15),
 ('SIG-085','T1190','SQL injection stacked queries',           'Multiple SQL statements via semicolon',                           8,'; drop table|; insert into|stacked query',          0.10),
 ('SIG-086','T1190','SQL injection NoSQL',                     'NoSQL injection (MongoDB $ne, $gt ...)',                          7,'$ne|$gt|$where|$regex',                             0.15),
 ('SIG-087','T1190','XSS reflected script tag',                '<script> tag in URL parameters',                                  7,'<script>|%3Cscript|javascript:',                    0.15),
 ('SIG-088','T1190','XSS stored payload',                      'XSS payload stored in request body',                              7,'onerror=|onload=|<img src=x',                       0.15),
 ('SIG-089','T1190','XSS DOM-based',                           'Document.cookie / location manipulation',                         6,'document.cookie|document.location|eval(',           0.20),
 ('SIG-090','T1190','LFI (Local File Inclusion)',              '../ path traversal to read /etc/passwd',                          8,'../../../|etc/passwd|../windows/system32',          0.10),
 ('SIG-091','T1190','RFI (Remote File Inclusion)',             'PHP include of external URL',                                     8,'http://|?file=http|?page=http',                     0.15),
 ('SIG-092','T1190','Path traversal URL encoded',              '%2e%2e%2f encoded traversal',                                     7,'%2e%2e%2f|%252e%252e|..%2F',                        0.10),
 ('SIG-093','T1059.004','OS command injection',                'Shell metacharacters in HTTP parameter',                          9,'; cat|; ls|; whoami|` |$(',                         0.10),
 ('SIG-094','T1190','Server-side template injection',          'SSTI Jinja / Twig / Freemarker',                                  8,'{{7*7}}|${{|<%=|#{7*7}',                            0.15),
 ('SIG-095','T1190','XXE external entity',                     'XML external entity injection',                                   8,'<!ENTITY|SYSTEM "file://|xxe',                      0.15),
 ('SIG-096','T1190','SSRF to internal metadata',               'SSRF to 169.254.169.254 / localhost',                             9,'169.254.169.254|127.0.0.1|localhost|metadata',      0.10),
 ('SIG-097','T1190','CRLF injection',                          'CRLF characters to split HTTP response',                          6,'%0d%0a|%0a|crlf injection',                         0.20),
 ('SIG-098','T1190','Open redirect',                           'Arbitrary redirect via URL param',                                4,'?redirect=http|?url=http|?next=http',               0.40),
 ('SIG-099','T1505.003','PHP web shell upload',                'Upload of .php file via HTTP POST',                               9,'.php?cmd=|c99|r57|webshell|eval($_',                0.10),
 ('SIG-100','T1505.003','JSP web shell',                       'JSP-based web shell',                                             9,'.jsp?cmd=|cmd.jsp|jspshell',                        0.10),
 ('SIG-101','T1505.003','ASPX web shell',                      'ASPX-based web shell',                                            9,'.aspx?cmd=|cmd.aspx|aspxshell',                     0.10),
 ('SIG-102','T1505.003','China Chopper backdoor',              'Known China Chopper web shell pattern',                          10,'china chopper|<?php @eval($_POST',                   0.05),
 ('SIG-103','T1505.003','WSO shell',                           'WSO PHP web shell',                                              10,'WSO|wso shell',                                     0.05),
 ('SIG-104','T1190','WordPress RCE',                           'WordPress plugin exploitation',                                   9,'wp-content/plugins|?page=wp|admin-ajax.php',        0.15),
 ('SIG-105','T1190','Drupalgeddon2 (CVE-2018-7600)',           'Drupal form array RCE',                                           9,'drupalgeddon|form_id=user_pass',                    0.10),
 ('SIG-106','T1190','Struts2 OGNL injection',                  'Apache Struts OGNL RCE',                                          9,'struts2|ognl|Content-Type: %{',                     0.10),
 ('SIG-107','T1190','Spring4Shell (CVE-2022-22965)',           'Spring Framework class.module.classLoader',                       9,'class.module.classLoader|spring4shell',             0.10),
 ('SIG-108','T1190','Log4Shell (CVE-2021-44228)',              'JNDI lookup payload',                                            10,'${jndi:ldap|${jndi:rmi|${jndi:dns',                  0.05),
 ('SIG-109','T1190','Apache Path Traversal (CVE-2021-41773)',  'Apache 2.4.49 path traversal',                                    9,'/cgi-bin/.%2e/|2021-41773',                         0.10),
 ('SIG-110','T1190','GitLab CVE-2021-22205',                   'GitLab unauth RCE',                                               9,'/uploads/user|cve-2021-22205',                      0.10),
 ('SIG-111','T1190','Jenkins exploit',                         'Jenkins CLI / script console RCE',                                8,'/cli?remoting=|jenkins script',                     0.15),
 ('SIG-112','T1190','Tomcat Manager deploy exploit',           'Unauthenticated Tomcat Manager /deploy',                          8,'tomcat/manager/html/deploy|manager/text',           0.15),
 ('SIG-113','T1190','ProxyLogon (CVE-2021-26855)',             'Exchange SSRF',                                                  10,'proxylogon|autodiscover.xml|/owa/auth/',            0.05),
 ('SIG-114','T1190','ProxyShell (CVE-2021-34473)',             'Exchange PowerShell SSRF',                                       10,'proxyshell|autodiscover/|X-Rps-CAT',                0.05),
 ('SIG-115','T1190','Confluence CVE-2022-26134',               'Atlassian Confluence OGNL',                                       9,'confluence|ognl|%24%7B',                            0.10),
 ('SIG-116','T1190','VMware vCenter CVE-2021-21985',           'vCenter vsphere-ui RCE',                                          9,'/ui/h5-vsan|vsphere-client',                        0.10),
 ('SIG-117','T1190','F5 BIG-IP CVE-2022-1388',                 'BIG-IP iControl REST auth bypass',                                9,'X-F5-Auth-Token|iControl|/mgmt/tm',                 0.10),
 ('SIG-118','T1190','Citrix ADC CVE-2019-19781',               'Citrix path traversal',                                           9,'/vpn/../vpns/|NSC_USER|citrix',                     0.10),
 ('SIG-119','T1190','PHP-FPM CVE-2019-11043',                  'PHP-FPM underflow RCE',                                           8,'php-fpm|\\x00\\x00\\x00\\x00|fpm underflow',        0.15),
 ('SIG-120','T1190','Nginx alias misconfig',                   'Path confusion due to alias directive',                           5,'/static../|alias traversal',                        0.25),
 ('SIG-121','T1190','Joomla RCE',                              'Joomla user-agent object injection',                              8,'joomla session|O:21:"Joomla',                       0.15),
 ('SIG-122','T1190','Magento RCE CVE-2022-24086',              'Magento checkout template injection',                             9,'magento|{{config path=|xcheckout',                  0.10),
 ('SIG-123','T1190','SharePoint CVE-2019-0604',                'SharePoint XML deserialization',                                 10,'sharepoint|_layouts/15/Picker.aspx',                0.10),
 ('SIG-124','T1190','GitLab RCE via ExifTool',                 'Unauth RCE via image upload',                                    10,'exiftool|CVE-2021-22205',                           0.10),
 ('SIG-125','T1190','Weblogic T3 CVE-2020-2883',               'Oracle Weblogic T3 deserialization',                              9,'weblogic|t3://|coherence',                          0.10),
 ('SIG-126','T1190','MOVEit Transfer CVE-2023-34362',          'Progress MOVEit SQLi to RCE',                                    10,'moveit|/human.aspx|moveit.dmz',                     0.05),
 ('SIG-127','T1190','Ivanti Connect Secure CVE-2023-46805',    'Ivanti ICS auth bypass',                                         10,'ivanti|connect secure|/api/v1/totp',                0.05),
 ('SIG-128','T1190','Fortinet Fortigate CVE-2024-21762',       'FortiOS SSL-VPN out-of-bounds write',                            10,'fortinet|ssl vpn|cve-2024-21762',                   0.05),
 ('SIG-129','T1190','CrushFTP CVE-2024-4040',                  'CrushFTP VFS sandbox escape',                                    10,'crushftp|vfs escape',                               0.05),
 ('SIG-130','T1190','PaperCut CVE-2023-27350',                 'PaperCut NG auth bypass RCE',                                    10,'papercut|SetupCompleted|9191',                      0.05),
 ('SIG-131','T1190','Fortra GoAnywhere CVE-2023-0669',         'GoAnywhere MFT RCE',                                             10,'goanywhere|LicenseResponseServlet',                 0.05),
 ('SIG-132','T1190','Argo CD path traversal',                  'Argo CD API path traversal',                                      7,'argocd|/api/v1|repo creds',                         0.20),
 ('SIG-133','T1190','Kubernetes API unauth access',            'Unauth read on kube-apiserver',                                   8,'/api/v1/pods|kube-apiserver anonymous',             0.15),
 ('SIG-134','T1190','Docker API exposed',                      'Unauthenticated Docker API on 2375',                              8,'docker api 2375|/v1.4[0-9]+/containers',            0.15),
 ('SIG-135','T1190','Redis unauth exposed',                    'Open Redis without auth',                                         7,'redis CONFIG SET|redis unauth',                     0.20),
 ('SIG-136','T1190','MongoDB unauth exposed',                  'Open MongoDB without auth',                                       7,'mongo not authorized|admin command',                0.20),
 ('SIG-137','T1190','Elasticsearch unauth exposed',            'Open Elasticsearch without auth',                                 7,'elasticsearch|_cat/indices',                        0.20),
 ('SIG-138','T1190','Jupyter Notebook unauth',                 'Open Jupyter without token',                                      8,'jupyter|/tree|notebook unauth',                     0.15),
 ('SIG-139','T1190','Spring Boot Actuator exposed',            'Public /actuator/env',                                            6,'/actuator/env|/actuator/heapdump',                  0.25),
 ('SIG-140','T1190','Prometheus metrics exposed',              'Public /metrics with internal info',                              5,'/metrics prometheus|node_exporter',                 0.40);

-- --- Block 4 : Exploitation / memory corruption (SIG-141..180) --
INSERT OR REPLACE INTO signatures (id, technique_id, name, description, severity, keywords, fp_likelihood) VALUES
 ('SIG-141','T1068','Linux kernel exploit CVE-2022-0847',      'Dirty Pipe',                                                      9,'dirty pipe|CVE-2022-0847',                          0.10),
 ('SIG-142','T1068','Linux kernel exploit CVE-2022-2588',      'cls_route UAF',                                                   9,'cls_route|CVE-2022-2588',                           0.10),
 ('SIG-143','T1068','PwnKit CVE-2021-4034',                    'pkexec local priv esc',                                           9,'pwnkit|pkexec|CVE-2021-4034',                       0.10),
 ('SIG-144','T1068','Looney Tunables CVE-2023-4911',           'glibc dynamic linker exploit',                                    9,'looney tunables|GLIBC_TUNABLES',                    0.10),
 ('SIG-145','T1068','OverlayFS CVE-2023-0386',                 'Ubuntu overlayfs priv esc',                                       9,'overlayfs|CVE-2023-0386',                           0.10),
 ('SIG-146','T1068','Nimbuspwn CVE-2022-29799',                'Linux priv esc via networkd-dispatcher',                          8,'nimbuspwn|networkd-dispatcher',                     0.10),
 ('SIG-147','T1068','CVE-2023-22515 Confluence admin create',  'Confluence privilege escalation',                                 9,'/setup/|userInviteFinished',                        0.10),
 ('SIG-148','T1203','Microsoft Office DDE exploit',            'Excel/Word DDE code execution',                                   7,'DDEAUTO|cmd /k',                                    0.15),
 ('SIG-149','T1203','Follina CVE-2022-30190',                  'ms-msdt: URI exploit',                                            9,'ms-msdt|follina|invoke-restmethod',                 0.10),
 ('SIG-150','T1203','Browser exploit kit',                     'Magnitude / RIG / Fallout EK patterns',                           9,'exploit kit|magnitude|rig ek',                      0.10),
 ('SIG-151','T1190','Heartbleed CVE-2014-0160',                'OpenSSL memory disclosure',                                       8,'heartbleed|TLS heartbeat|CVE-2014-0160',            0.10),
 ('SIG-152','T1190','Shellshock CVE-2014-6271',                'Bash env function exploit',                                       9,'() { :;}|shellshock|CVE-2014-6271',                 0.10),
 ('SIG-153','T1190','Poodle CVE-2014-3566',                    'SSLv3 downgrade exploit',                                         4,'POODLE|SSLv3 downgrade',                            0.25),
 ('SIG-154','T1190','BlueKeep CVE-2019-0708',                  'RDP pre-auth RCE',                                                9,'bluekeep|CVE-2019-0708|rdp preauth',                0.10),
 ('SIG-155','T1190','EternalBlue CVE-2017-0144',               'SMBv1 exploit',                                                  10,'eternalblue|ms17-010|smb exploit',                  0.05),
 ('SIG-156','T1190','SMBGhost CVE-2020-0796',                  'SMBv3 compression overflow',                                      9,'smbghost|CVE-2020-0796',                            0.10),
 ('SIG-157','T1190','ZeroLogon CVE-2020-1472',                 'Netlogon elevation of privilege',                                10,'zerologon|CVE-2020-1472|netlogon',                  0.05),
 ('SIG-158','T1190','PrintNightmare CVE-2021-34527',           'Windows Print Spooler RCE',                                      10,'printnightmare|spoolsv|CVE-2021-34527',              0.05),
 ('SIG-159','T1190','SIGRed CVE-2020-1350',                    'Windows DNS server RCE',                                         10,'sigred|CVE-2020-1350',                              0.05),
 ('SIG-160','T1190','HAFNIUM Exchange exploit',                'HAFNIUM Exchange chain',                                         10,'hafnium|ProxyLogon|ProxyShell',                     0.05),
 ('SIG-161','T1059.004','Reverse shell bash',                  'bash reverse shell pattern',                                      9,'bash -i >& /dev/tcp|/bin/bash -i',                  0.10),
 ('SIG-162','T1059.006','Reverse shell python',                'python reverse shell pattern',                                    9,'python -c ''import socket|python -c import os',     0.10),
 ('SIG-163','T1059.001','Reverse shell powershell',            'PowerShell reverse shell',                                        9,'powershell -nop -c|Invoke-Expression|iex',          0.10),
 ('SIG-164','T1059.007','Reverse shell node.js',               'Node.js reverse shell',                                           8,'require(''child_process'').exec',                   0.15),
 ('SIG-165','T1059.003','cmd.exe suspicious execution',        'cmd.exe spawned by web server',                                   8,'cmd.exe|w3wp.exe -> cmd',                           0.15),
 ('SIG-166','T1059.001','PowerShell encoded command',          'Base64 -EncodedCommand abuse',                                    8,'powershell -enc|-EncodedCommand|-nop',              0.15),
 ('SIG-167','T1059.001','PowerShell IEX download',             'iex (New-Object Net.WebClient)',                                  8,'iex (new-object|downloadstring',                    0.15),
 ('SIG-168','T1105','certutil.exe download',                   'LOLBIN download via certutil',                                    7,'certutil -urlcache|certutil -f',                    0.20),
 ('SIG-169','T1105','bitsadmin download',                      'LOLBIN download via bitsadmin',                                   7,'bitsadmin /transfer|bitsadmin',                     0.20),
 ('SIG-170','T1105','mshta.exe download',                      'LOLBIN HTA execution',                                            7,'mshta.exe|hta http',                                0.20),
 ('SIG-171','T1105','regsvr32 squiblydoo',                     'regsvr32 remote scrobj',                                          8,'regsvr32 /s /n /u /i:http|scrobj.dll',              0.15),
 ('SIG-172','T1105','wget / curl download to /tmp',            'Download binary to /tmp from shell',                              7,'wget http|curl http|/tmp/',                         0.25),
 ('SIG-173','T1105','PowerShell Invoke-WebRequest',            'PowerShell IWR file download',                                    6,'invoke-webrequest|iwr -uri',                        0.30),
 ('SIG-174','T1203','Flash SWF exploit',                       'Malicious SWF in HTTP response',                                  7,'application/x-shockwave-flash|CVE-2018-4878',       0.15),
 ('SIG-175','T1203','Office macro execution',                  'VBA macro with suspicious keywords',                              7,'AutoOpen|Shell(|vba macro',                         0.20),
 ('SIG-176','T1055','Process hollowing pattern',               'CreateProcess with suspended flag + unmap',                       9,'NtUnmapViewOfSection|process hollowing',            0.15),
 ('SIG-177','T1055','Reflective DLL injection',                'LoadLibrary via VirtualAllocEx pattern',                          9,'VirtualAllocEx|WriteProcessMemory|reflective',      0.15),
 ('SIG-178','T1055','Linux LD_PRELOAD injection',              'LD_PRELOAD environment used for injection',                       7,'LD_PRELOAD=|ld.so.preload',                         0.20),
 ('SIG-179','T1134','Token impersonation',                     'DuplicateTokenEx / ImpersonateLoggedOnUser',                      8,'DuplicateTokenEx|ImpersonateLoggedOnUser',          0.15),
 ('SIG-180','T1203','Java deserialization RCE',                'Known gadget chain in HTTP body',                                 8,'commons-collections|ysoserial|CommonsBeanutils',    0.15);

-- --- Block 5 : Malware & C2 (SIG-181..225) ----------------------
INSERT OR REPLACE INTO signatures (id, technique_id, name, description, severity, keywords, fp_likelihood) VALUES
 ('SIG-181','T1071.001','Cobalt Strike beacon',                'CS Malleable profile HTTP patterns',                             10,'cobalt strike|malleable|beacon.dll',                0.05),
 ('SIG-182','T1071.001','Metasploit meterpreter HTTP',         'Meterpreter HTTP/HTTPS payloads',                                 9,'meterpreter|metasploit payload|HTTP/1.1 200 OK\\r\\n',0.10),
 ('SIG-183','T1071.001','Sliver implant',                      'Sliver C2 framework',                                             9,'sliver|sliver/|sliverc2',                           0.10),
 ('SIG-184','T1071.001','Mythic C2 traffic',                   'Mythic framework patterns',                                       9,'mythic|apfell|poseidon c2',                         0.10),
 ('SIG-185','T1071.001','Havoc framework',                     'Havoc C2 framework',                                              9,'havoc|demon.dll',                                   0.10),
 ('SIG-186','T1071.001','Merlin HTTP/2 C2',                    'Merlin post-exploitation',                                        9,'merlinagent|merlin c2',                             0.10),
 ('SIG-187','T1071.001','PoshC2 beacon',                       'PoshC2 framework patterns',                                       9,'poshc2|implant-handler.py',                         0.10),
 ('SIG-188','T1071.001','Empire C2 beacon',                    'PowerShell Empire beacon',                                        9,'powershell empire|empire c2',                       0.10),
 ('SIG-189','T1071.004','DNS tunneling',                       'Base64 / long subdomain beacons',                                 7,'dns tunnel|iodine|dnscat',                          0.20),
 ('SIG-190','T1071.001','Raw JSON C2 pattern',                 'GET /jquery-3.3.1.min.js suspicious host',                        5,'jquery-3.3.1|/jquery-|fake jquery',                 0.30),
 ('SIG-191','T1572','DNS over HTTPS beacon',                   'DoH used for covert C2',                                          6,'dns.google/dns-query|cloudflare-dns.com/dns-query', 0.30),
 ('SIG-192','T1095','ICMP tunneling',                          'Data in ICMP payload',                                            7,'icmp tunnel|ptunnel|icmpsh',                        0.20),
 ('SIG-193','T1571','C2 on non-standard port',                 'Known C2 on ephemeral high port',                                 6,'port 4444|port 6666|port 7777',                     0.30),
 ('SIG-194','T1090','Tor exit node connection',                'Outbound connection to known Tor exit',                           6,'tor exit|onion|9050',                               0.35),
 ('SIG-195','T1090','I2P network connection',                  'I2P anonymizing network',                                         5,'i2p|.i2p',                                          0.40),
 ('SIG-196','T1573','Self-signed TLS to rare host',            'TLS handshake with self-signed cert',                             4,'self signed cert|x509 unknown issuer',              0.50),
 ('SIG-197','T1486','Ransomware extension pattern',            'Files renamed with .locked / .crypt / .encrypted',                9,'.locked|.crypt|.encrypted|.ransom',                 0.10),
 ('SIG-198','T1486','LockBit ransomware',                      'LockBit 3.0 / Black patterns',                                   10,'lockbit|lockbit3|lockbit black',                    0.05),
 ('SIG-199','T1486','BlackCat / ALPHV ransomware',             'BlackCat ALPHV Rust ransomware',                                 10,'blackcat|alphv|noberus',                            0.05),
 ('SIG-200','T1486','BlackBasta ransomware',                   'BlackBasta ransomware indicators',                               10,'blackbasta|basta',                                  0.05),
 ('SIG-201','T1486','Akira ransomware',                        'Akira ransomware pattern',                                       10,'akira ransomware|.akira',                           0.05),
 ('SIG-202','T1486','Royal ransomware',                        'Royal ransomware pattern',                                       10,'royal ransomware|.royal',                           0.05),
 ('SIG-203','T1486','Play ransomware',                         'Play ransomware pattern',                                        10,'play ransomware|.play',                             0.05),
 ('SIG-204','T1486','Vice Society ransomware',                 'Vice Society pattern',                                           10,'vice society',                                      0.05),
 ('SIG-205','T1486','Hive ransomware',                         'Hive ransomware pattern',                                        10,'hive ransomware|.hive',                             0.05),
 ('SIG-206','T1496','XMRig crypto miner',                      'Monero mining binary pattern',                                    7,'xmrig|stratum+tcp|minerd',                          0.15),
 ('SIG-207','T1496','MinerGate pool traffic',                  'Outbound to known mining pool',                                   6,'minergate|xmrpool|nanopool',                        0.20),
 ('SIG-208','T1496','CPU high usage w/ mining DNS',            'Suspicious high CPU + mining DNS',                                5,'mining pool|stratum protocol',                      0.25),
 ('SIG-209','T1071.001','Qakbot C2',                           'Qakbot banking trojan',                                          10,'qakbot|qbot|pinkslip',                              0.05),
 ('SIG-210','T1071.001','TrickBot C2',                         'TrickBot patterns',                                              10,'trickbot|trickloader',                              0.05),
 ('SIG-211','T1071.001','Emotet C2',                           'Emotet patterns',                                                10,'emotet|heodo',                                      0.05),
 ('SIG-212','T1071.001','IcedID C2',                           'IcedID banking trojan',                                          10,'icedid|bokbot',                                     0.05),
 ('SIG-213','T1071.001','BumbleBee loader',                    'BumbleBee loader patterns',                                       9,'bumblebee|bumblebee loader',                        0.10),
 ('SIG-214','T1071.001','SocGholish fakeupdate',               'SocGholish JS loader',                                            9,'fakeupdates|socgholish|update_chrome',              0.10),
 ('SIG-215','T1071.001','Gootloader',                          'Gootloader JS delivery',                                          9,'gootloader',                                        0.10),
 ('SIG-216','T1071.001','PikaBot loader',                      'PikaBot loader patterns',                                         9,'pikabot|pikaloader',                                0.10),
 ('SIG-217','T1071.001','DanaBot',                             'DanaBot banking trojan',                                          9,'danabot|danabot c2',                                0.10),
 ('SIG-218','T1071.001','AsyncRAT',                            'AsyncRAT payload',                                                9,'asyncrat|asyncrat c2',                              0.10),
 ('SIG-219','T1071.001','NjRAT',                               'NjRAT payload',                                                   9,'njrat|njrat c2',                                    0.10),
 ('SIG-220','T1071.001','Remcos RAT',                          'Remcos RAT',                                                      9,'remcos|remcos rat',                                 0.10),
 ('SIG-221','T1071.001','Agent Tesla',                         'Agent Tesla info stealer',                                       10,'agent tesla|tesla stealer',                         0.05),
 ('SIG-222','T1071.001','FormBook info stealer',               'FormBook info stealer',                                          10,'formbook|formbook c2',                              0.05),
 ('SIG-223','T1071.001','Lumma stealer',                       'Lumma info stealer',                                             10,'lumma stealer|lumma c2',                            0.05),
 ('SIG-224','T1071.001','RedLine stealer',                     'RedLine info stealer',                                           10,'redline stealer|redline c2',                        0.05),
 ('SIG-225','T1071.001','Raccoon stealer',                     'Raccoon Stealer v2',                                             10,'raccoon stealer|raccoon v2',                        0.05);

-- --- Block 6 : Privilege escalation & persistence (SIG-226..265) --
INSERT OR REPLACE INTO signatures (id, technique_id, name, description, severity, keywords, fp_likelihood) VALUES
 ('SIG-226','T1548.003','Sudo misconfiguration exploit',       'Sudoers NOPASSWD abuse',                                          8,'sudo -l|NOPASSWD|sudoers',                          0.20),
 ('SIG-227','T1548.003','Sudo Baron Samedit CVE-2021-3156',    'sudo heap overflow',                                              9,'baron samedit|CVE-2021-3156',                       0.10),
 ('SIG-228','T1548.001','SUID binary abuse',                   'Execution of world-writable SUID',                                7,'find / -perm -4000|suid exploit',                   0.25),
 ('SIG-229','T1068','DirtyCow CVE-2016-5195',                  'Linux DirtyCow race condition',                                   9,'dirtycow|CVE-2016-5195',                            0.10),
 ('SIG-230','T1098','Linux passwd modification',               'Write to /etc/passwd',                                            8,'echo ::0:0|usermod root',                           0.15),
 ('SIG-231','T1098','Linux shadow modification',               'Write to /etc/shadow',                                            9,'echo root:|chpasswd|usermod -p',                    0.10),
 ('SIG-232','T1136','New local account created',               'useradd / net user / adduser event',                              6,'useradd|adduser|net user /add',                     0.25),
 ('SIG-233','T1136','New domain user created',                 'Net user /domain add',                                            8,'net user /domain /add|ldap modify add user',        0.15),
 ('SIG-234','T1136','SSH authorized_keys modification',        'Write to authorized_keys by non-user',                            8,'.ssh/authorized_keys|authorized_keys2',             0.15),
 ('SIG-235','T1543.002','Malicious systemd service',           'New .service file created',                                       7,'systemd new service|/etc/systemd/system/',          0.25),
 ('SIG-236','T1543','New Windows service',                     'New service created via sc.exe',                                  7,'sc.exe create|New-Service',                         0.25),
 ('SIG-237','T1547','HKCU Run key modified',                   'Registry run key persistence',                                    8,'HKCU\\\\Software\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Run',0.15),
 ('SIG-238','T1547','HKLM Run key modified',                   'Registry run key machine-wide',                                   8,'HKLM\\\\Software\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Run',0.15),
 ('SIG-239','T1547','Winlogon shell replaced',                 'Winlogon Shell key modified',                                     9,'Winlogon|\\\\Shell',                                0.10),
 ('SIG-240','T1053.003','Suspicious cron entry',               'New cron job with reverse shell',                                 7,'crontab|/etc/cron.d|cron reverse',                  0.20),
 ('SIG-241','T1053.005','Suspicious scheduled task',           'schtasks creating task with PowerShell',                          7,'schtasks /create|Register-ScheduledTask',           0.20),
 ('SIG-242','T1098','Linux root password changed',             'passwd changed for root outside maintenance window',              8,'passwd root|password change for root',              0.20),
 ('SIG-243','T1037','/etc/rc.local modification',              'Write to /etc/rc.local for persistence',                          7,'/etc/rc.local|rc.local modified',                   0.20),
 ('SIG-244','T1037','Linux .bashrc persistence',               'Evil commands appended to .bashrc',                               6,'.bashrc|.bash_profile persistence',                 0.25),
 ('SIG-245','T1037','Windows startup folder drop',             'New file in Startup folder',                                      7,'Startup|\\\\Start Menu\\\\Programs\\\\Startup',     0.20),
 ('SIG-246','T1546','WMI event subscription',                  'Event consumer + filter for WMI persistence',                     8,'wmi event|__EventFilter|CommandLineTemplate',       0.15),
 ('SIG-247','T1547','BootExecute registry modified',           'BootExecute subkey changed',                                      9,'BootExecute|smss.exe',                              0.10),
 ('SIG-248','T1098','AD group membership change',              'User added to privileged group',                                  7,'Domain Admins|Enterprise Admins|member added',      0.20),
 ('SIG-249','T1098','Local admin group change',                'User added to local admins',                                      7,'Administrators|net localgroup administrators',      0.20),
 ('SIG-250','T1562.001','Windows Defender disabled',           'Set-MpPreference -DisableRealtimeMonitoring',                     8,'Set-MpPreference|DisableRealtimeMonitoring',        0.10),
 ('SIG-251','T1562.001','AV service stopped',                  'Stop-Service / sc stop for AV',                                   8,'stop-service|sc stop|sense.exe',                    0.15),
 ('SIG-252','T1562.001','EDR driver unloaded',                 'Unusual fltmc / driver unload of EDR',                            9,'fltmc unload|sc delete edr',                        0.10),
 ('SIG-253','T1562.004','Windows Firewall rule disabled',      'netsh firewall set opmode disable',                               7,'netsh advfirewall|set profile state off',           0.15),
 ('SIG-254','T1562.004','iptables flush',                      'iptables -F / nftables flush',                                    7,'iptables -F|nftables flush|firewall disable',       0.15),
 ('SIG-255','T1562','Selinux disabled',                        'setenforce 0 / SELINUX=disabled',                                 7,'setenforce 0|SELINUX=disabled',                     0.15),
 ('SIG-256','T1562','AppArmor disabled',                       'systemctl stop apparmor',                                         7,'apparmor disable|aa-disable',                       0.15),
 ('SIG-257','T1070.002','Clear Linux syslog',                  '>/var/log/syslog or rm -rf /var/log',                             7,'clear /var/log|> /var/log/syslog',                  0.20),
 ('SIG-258','T1070','Windows event log cleared',               '4104/1102 indicating log clear',                                  8,'EventLog cleared|Security log cleared|1102',        0.10),
 ('SIG-259','T1070.004','Secure delete pattern',               'shred / sdelete usage',                                           6,'shred|sdelete|wipe',                                0.25),
 ('SIG-260','T1027','Obfuscated PowerShell',                   'Highly obfuscated / base64 PS payload',                           7,'FromBase64String|[char]|-join',                     0.20),
 ('SIG-261','T1027','XOR-encoded payload',                     'XOR patterns in HTTP body',                                       6,'xor 0x|decoder stub',                               0.25),
 ('SIG-262','T1027','Hex-encoded shell command',               'Shell command hex encoded',                                       6,'\\\\x68\\\\x74\\\\x74\\\\x70|hex encoded',          0.25),
 ('SIG-263','T1068','Windows kernel token theft',              'Token stealing shellcode pattern',                                9,'SYSTEM_PROCESS_INFORMATION|token theft',            0.10),
 ('SIG-264','T1134','RunAs spawned unusual process',           'runas /user:SYSTEM calc.exe',                                     7,'runas /user|elevated shell',                        0.20),
 ('SIG-265','T1548','UAC bypass (fodhelper)',                  'Known UAC bypass via fodhelper',                                  8,'fodhelper|UAC bypass',                              0.15);

-- --- Block 7 : Lateral movement & discovery (SIG-266..300) ------
INSERT OR REPLACE INTO signatures (id, technique_id, name, description, severity, keywords, fp_likelihood) VALUES
 ('SIG-266','T1021.001','RDP internal lateral',                'RDP connection between internal hosts',                           6,'rdp internal|mstsc|3389 internal',                  0.30),
 ('SIG-267','T1021.002','SMB PSExec',                          'PSExec over SMB',                                                 8,'psexec|psexesvc',                                   0.15),
 ('SIG-268','T1021.002','Impacket wmiexec',                    'Impacket wmiexec / smbexec',                                      8,'wmiexec|smbexec|impacket',                          0.15),
 ('SIG-269','T1021.004','SSH internal lateral',                'SSH from internal host to internal host',                         5,'ssh internal|internal lateral ssh',                 0.40),
 ('SIG-270','T1021','WinRM lateral',                           'WinRM from unusual source',                                       7,'winrm|wsman|5985|5986',                             0.25),
 ('SIG-271','T1021','DCOM lateral',                            'DCOM MMC20 / ShellExecute',                                       7,'dcom lateral|MMC20.Application',                    0.20),
 ('SIG-272','T1570','Tool transfer via SMB',                   'Executable copied to admin share',                                8,'ADMIN$|C$ executable copy',                         0.15),
 ('SIG-273','T1021','Pass-the-Hash',                           'NTLM auth with stolen hash',                                      9,'pass the hash|pth|PtH',                             0.10),
 ('SIG-274','T1021','Pass-the-Ticket',                         'Kerberos ticket injection',                                       9,'pass the ticket|ptt|kirbi',                         0.10),
 ('SIG-275','T1046','CrackMapExec scan',                       'CMEs SMB / WinRM / MSSQL enumeration',                            8,'crackmapexec|cme',                                  0.15),
 ('SIG-276','T1046','BloodHound collection',                   'SharpHound / AzureHound data collection',                         8,'sharphound|bloodhound',                             0.15),
 ('SIG-277','T1087','LDAP user enumeration',                   'LDAP query for all users',                                        5,'(objectClass=user)|ldap enumeration',               0.35),
 ('SIG-278','T1018','Ping sweep internal',                     'ICMP sweep from internal host',                                   4,'internal ping sweep|icmp echo',                     0.40),
 ('SIG-279','T1018','ARP scan internal',                       'arp-scan across internal subnet',                                 4,'internal arp scan|arp-scan subnet',                 0.40),
 ('SIG-280','T1018','Nmap from internal host',                 'Internal nmap scan',                                              6,'nmap -sS internal|internal scan',                   0.30),
 ('SIG-281','T1082','whoami / id / hostname burst',            'Reconnaissance commands in short window',                         4,'whoami;id;hostname|id && whoami',                   0.35),
 ('SIG-282','T1082','systeminfo execution',                    'systeminfo.exe output',                                           4,'systeminfo|Host Name:|OS Name:',                    0.40),
 ('SIG-283','T1082','uname -a on production server',           'uname -a by web process',                                         4,'uname -a|kernel release',                           0.45),
 ('SIG-284','T1135','net view \\\\\\\\host',                   'Net view of another host',                                        5,'net view|\\\\\\\\\\\\\\\\',                         0.30),
 ('SIG-285','T1135','smbclient enumeration',                   'smbclient -L list shares',                                        5,'smbclient -L|smbclient //',                         0.30),
 ('SIG-286','T1016','ipconfig / ifconfig burst',               'Net config discovery commands',                                   3,'ipconfig|ifconfig|ip addr',                         0.55),
 ('SIG-287','T1016','route print',                             'Routing table discovery',                                         3,'route print|ip route',                              0.55),
 ('SIG-288','T1057','tasklist / ps aux enumeration',           'Process listing by unusual user',                                 3,'tasklist|ps aux',                                   0.60),
 ('SIG-289','T1083','find / read by web user',                 'find / -name executed by www-data',                               5,'find /|www-data find',                              0.30),
 ('SIG-290','T1083','dir /s /b recursive',                     'Recursive file listing',                                          3,'dir /s /b|Get-ChildItem -Recurse',                  0.55),
 ('SIG-291','T1087','net user enumeration',                    'net user / net group commands',                                   4,'net user|net group',                                0.40),
 ('SIG-292','T1087','Get-ADUser / Get-ADGroup abuse',          'ActiveDirectory powershell queries',                              4,'Get-ADUser|Get-ADGroup|Get-ADComputer',             0.40),
 ('SIG-293','T1080','SMB share file tampering',                'Write to shared file by unusual user',                            7,'SMB write|shared file modified',                    0.25),
 ('SIG-294','T1021.001','RDP brute force + success',           'RDP failed × N then success',                                     8,'4625 then 4624|rdp failed then success',            0.10),
 ('SIG-295','T1021.002','SMB admin share access',              'Access to ADMIN$ / IPC$ / C$',                                    6,'ADMIN$|IPC$|C$',                                    0.25),
 ('SIG-296','T1021','Golden Ticket',                           'krbtgt TGT with long lifetime',                                  10,'golden ticket|mimikatz golden|krbtgt',               0.05),
 ('SIG-297','T1021','Silver Ticket',                           'Service ticket forgery',                                         10,'silver ticket|service ticket forge',                 0.05),
 ('SIG-298','T1021.004','SSH key addition',                    'authorized_keys modified via SMB lateral',                        8,'authorized_keys via smb|ssh key lateral',           0.15),
 ('SIG-299','T1021','Remote WMI execution',                    'WMI Win32_Process.Create remote',                                 8,'Invoke-WmiMethod|Win32_Process.Create',             0.15),
 ('SIG-300','T1570','Copy to remote C$',                       'File copy to \\\\host\\\\C$ from workstation',                    7,'copy \\\\\\\\host\\\\C$|xcopy C$',                  0.20);

-- --- Block 8 : Exfiltration & impact (SIG-301..340) ------------
INSERT OR REPLACE INTO signatures (id, technique_id, name, description, severity, keywords, fp_likelihood) VALUES
 ('SIG-301','T1560','Large rar / 7z archive created',          'Creation of huge archive before exfil',                           5,'rar a|7z a|large archive',                          0.35),
 ('SIG-302','T1560','Password-protected archive',              'rar / zip created with -p password',                              5,'rar -p|7z -p|zip -P',                               0.30),
 ('SIG-303','T1005','Database full dump',                      'mysqldump / pg_dumpall',                                          6,'mysqldump|pg_dumpall|pg_dump',                      0.30),
 ('SIG-304','T1005','File read burst',                         'One process reads many files rapidly',                            5,'file read burst|mass read',                         0.35),
 ('SIG-305','T1039','SMB share copy large',                    'Large file pulled from share',                                    6,'SMB large copy|share exfil',                        0.30),
 ('SIG-306','T1041','POST to rare external IP',                'HTTP POST of large payload to new IP',                            7,'POST large|exfil c2',                               0.20),
 ('SIG-307','T1048','FTP upload to external',                  'Outbound FTP STOR to external',                                   6,'ftp stor|ftp upload',                               0.25),
 ('SIG-308','T1048','SFTP / SCP to external',                  'Outbound SSH file transfer',                                      6,'sftp put|scp to|rsync external',                    0.30),
 ('SIG-309','T1567','Upload to Mega / Dropbox / Google Drive', 'Exfil via cloud service',                                         6,'mega.nz|dropbox.com|drive.google.com',              0.35),
 ('SIG-310','T1567','Upload to transfer.sh',                   'Exfil to transfer.sh',                                            7,'transfer.sh|anonfiles.com',                         0.20),
 ('SIG-311','T1567','Upload to Pastebin',                      'Exfil to Pastebin-like service',                                  6,'pastebin.com|ghostbin|hastebin',                    0.25),
 ('SIG-312','T1567','Discord webhook exfil',                   'Exfil to Discord webhook',                                        7,'discord.com/api/webhooks|discordapp.com/api',       0.20),
 ('SIG-313','T1567','Telegram bot exfil',                      'Exfil to Telegram bot API',                                       7,'api.telegram.org/bot|sendDocument',                 0.20),
 ('SIG-314','T1041','DNS exfiltration long records',           'Long TXT / A chains',                                             7,'dns exfil|long txt record',                         0.20),
 ('SIG-315','T1029','Scheduled exfil transfer',                'Scheduled task triggers exfil outside work hours',                6,'scheduled exfil|off-hours transfer',                0.25),
 ('SIG-316','T1485','Massive file deletion',                   'Large scale rm / del',                                            8,'rm -rf|del /f /s|mass delete',                      0.15),
 ('SIG-317','T1485','MBR wiped',                               'dd of MBR / volume header',                                       9,'dd if=/dev/zero of=/dev/sda|wipe mbr',              0.05),
 ('SIG-318','T1486','Volume shadow copies deleted',            'vssadmin delete shadows',                                         9,'vssadmin delete shadows|wmic shadowcopy',           0.05),
 ('SIG-319','T1486','Backup catalog deleted',                  'wbadmin delete / veeam catalog wipe',                             9,'wbadmin delete|veeam catalog',                      0.05),
 ('SIG-320','T1486','Boot config disabled',                    'bcdedit /set recoveryenabled No',                                 8,'bcdedit /set recoveryenabled|bcdedit bootstatuspolicy',0.15),
 ('SIG-321','T1499','ICMP flood',                              'ICMP flood DDoS',                                                 6,'icmp flood|ping flood',                             0.25),
 ('SIG-322','T1498','SYN flood',                               'SYN flood',                                                       7,'syn flood|tcp syn flood',                           0.20),
 ('SIG-323','T1498','UDP flood',                               'UDP flood',                                                       6,'udp flood|udp ddos',                                0.25),
 ('SIG-324','T1498','DNS amplification',                       'DNS recursive amplification',                                     7,'dns amp|open resolver abuse',                       0.20),
 ('SIG-325','T1498','NTP amplification',                       'NTP monlist amplification',                                       7,'ntp monlist|ntp amp',                               0.15),
 ('SIG-326','T1498','Memcached amplification',                 'Memcached UDP amplification',                                     8,'memcached amp|udp 11211',                           0.10),
 ('SIG-327','T1498','SSDP amplification',                      'SSDP / UPnP amplification',                                       7,'ssdp amp|udp 1900',                                 0.20),
 ('SIG-328','T1491','Website defacement',                      'index.html replaced with defacement',                             7,'deface|h4ck3d|pwned',                               0.15),
 ('SIG-329','T1565','Log tampering',                           'Sensitive log entries modified in place',                         8,'log tamper|log modification',                       0.20),
 ('SIG-330','T1485','wbadmin disable',                         'Windows Server Backup disabled',                                  8,'wbadmin disable|wbadmin off',                       0.15),
 ('SIG-331','T1486','Recycle Bin purged forcibly',             'Forced Recycle Bin clear',                                        5,'recycle bin purge|Clear-RecycleBin',                0.40),
 ('SIG-332','T1485','Git history wiped',                       'git filter-branch / force push empty',                            5,'git filter-branch|force push empty',                0.35),
 ('SIG-333','T1486','Ransom note dropped',                     'README_DECRYPT / HOW_TO_DECRYPT files',                          10,'HOW_TO_DECRYPT|README_RESTORE|!recover',            0.05),
 ('SIG-334','T1486','Shadow copy volume deletion',             'DeviceIoControl shadow copy deletion',                            9,'IOCTL_VOLSNAP_FLUSH|shadow copy deletion',          0.10),
 ('SIG-335','T1486','Ransomware registry keys',                'Keys set by ransomware variants',                                 9,'RansomNote|ID-|Decryption-Id',                      0.10),
 ('SIG-336','T1496','Cryptojacking web worker',                'Coinhive / CryptoLoot JavaScript mining',                         6,'coinhive|cryptoloot|webminerpool',                  0.25),
 ('SIG-337','T1496','SSH brute-force then miner install',      'Succeeded SSH brute + xmrig',                                     9,'ssh success then xmrig|miner install',              0.10),
 ('SIG-338','T1499','Slowloris attack',                        'Slowloris low-bandwidth HTTP DoS',                                6,'slowloris|low bandwidth http',                      0.20),
 ('SIG-339','T1499','HTTP flood',                              'High rate HTTP GET / POST',                                       6,'http flood|hulk|loic',                              0.25),
 ('SIG-340','T1485','rm -rf / on production host',             'Catastrophic rm -rf /',                                          10,'rm -rf /|rm -rf /*',                                0.05);

-- --- Block 9 : Honeypot & specialized (SIG-341..380) ----------
INSERT OR REPLACE INTO signatures (id, technique_id, name, description, severity, keywords, fp_likelihood) VALUES
 ('SIG-341','T1110.001','Honeypot SSH connection',             'Any connection to honeypot SSH port 2222',                        8,'honeypot ssh|port 2222',                            0.05),
 ('SIG-342','T1110.001','Honeypot SSH login attempt',          'Login attempted on honeypot SSH',                                 9,'honeypot ssh login|2222 login',                     0.05),
 ('SIG-343','T1110.001','Honeypot SSH default creds',          'root/root, admin/admin, admin/password on honeypot',              9,'root:root|admin:admin|admin:password',              0.05),
 ('SIG-344','T1110.001','Honeypot HTTP connection',            'Connection to honeypot HTTP 8888',                                7,'honeypot http|port 8888',                           0.05),
 ('SIG-345','T1190','Honeypot HTTP admin path',                'Access to /admin or /wp-admin on honeypot',                       8,'honeypot admin|/wp-admin on honeypot',              0.05),
 ('SIG-346','T1110.001','Honeypot MySQL connection',           'Connection to honeypot MySQL 3307',                               8,'honeypot mysql|port 3307',                          0.05),
 ('SIG-347','T1110.001','Honeypot MySQL login',                'Login attempt on honeypot MySQL',                                 9,'honeypot mysql login',                              0.05),
 ('SIG-348','T1105','Honeypot file download attempt',          'wget / curl in honeypot session',                                 8,'honeypot wget|honeypot curl',                       0.05),
 ('SIG-349','T1105','Honeypot malware upload',                 'Binary uploaded to honeypot',                                    10,'honeypot binary upload',                            0.05),
 ('SIG-350','T1046','Honeypot port scan from one IP',          'Multiple honeypot ports from same IP',                            8,'multi honeypot port|honeypot portscan',             0.05),
 ('SIG-351','T1071.001','Honeypot IoT default creds',          'IoT default creds (Mirai / Hajime patterns)',                     9,'root:xc3511|admin:admin1234|mirai',                 0.05),
 ('SIG-352','T1190','Mirai-style telnet probe',                'Mirai-variant telnet 23/2323 probing',                            8,'/bin/busybox|mirai|telnet 23',                      0.10),
 ('SIG-353','T1190','Hikvision CVE-2021-36260',                'Hikvision RCE pattern',                                           9,'hikvision|CVE-2021-36260',                          0.10),
 ('SIG-354','T1190','D-Link router exploit',                   'Known D-Link unauth exec',                                        8,'d-link|/HNAP1/|dlink rce',                          0.10),
 ('SIG-355','T1190','Netgear router exploit',                  'Netgear DNS hijack',                                              8,'netgear|/currentsetting.htm',                       0.10),
 ('SIG-356','T1190','MikroTik WinBox CVE-2018-14847',          'MikroTik pre-auth file read',                                     9,'mikrotik|winbox|CVE-2018-14847',                    0.10),
 ('SIG-357','T1190','Pulse Secure CVE-2019-11510',             'Pulse Secure arbitrary file read',                                9,'pulse secure|/dana-na/|CVE-2019-11510',             0.10),
 ('SIG-358','T1190','SonicWall SMA CVE-2021-20038',            'SonicWall SMA stack overflow',                                    9,'sonicwall|sma100|CVE-2021-20038',                   0.10),
 ('SIG-359','T1190','QNAP NAS DeadBolt pattern',               'QNAP DeadBolt ransomware',                                       10,'deadbolt|qnap|.deadbolt',                           0.05),
 ('SIG-360','T1190','Synology attack pattern',                 'Synology bruteforce / exploits',                                  8,'synology|dsm login',                                0.15),
 ('SIG-361','T1110.001','Honeypot ICS Modbus probe',           'Modbus probe on honeypot',                                        9,'modbus honeypot|port 502',                          0.05),
 ('SIG-362','T1071.002','Honeypot FTP anonymous login',        'Anonymous FTP login attempt',                                     7,'anonymous FTP|ftp anonymous',                       0.15),
 ('SIG-363','T1110.001','SMB null session on honeypot',        'Null SMB session on honeypot 139 / 445',                          7,'null session|smb null',                             0.20),
 ('SIG-364','T1190','WebDAV PROPFIND recon',                   'WebDAV PROPFIND enumeration',                                     5,'PROPFIND|webdav',                                   0.30),
 ('SIG-365','T1046','TLS handshake probe no SNI',              'Mass TLS probes with no SNI',                                     4,'TLS no sni|tls probe',                              0.40),
 ('SIG-366','T1071.001','Malicious UA: Mozlila',               'Mozlila typo UA (malware)',                                       8,'Mozlila|Mozilla/4.75 (Nikto)',                      0.10),
 ('SIG-367','T1071.001','Empty User-Agent POST',               'HTTP POST with empty UA',                                         4,'empty user agent|UA: -',                            0.45),
 ('SIG-368','T1071.001','User-Agent masscan',                  'User-Agent: masscan',                                             6,'masscan|user-agent masscan',                        0.15),
 ('SIG-369','T1071.001','User-Agent zgrab',                    'User-Agent: zgrab',                                               5,'zgrab|user-agent zgrab',                            0.30),
 ('SIG-370','T1071.001','Request with shellshock headers',     'User-Agent () { :;}',                                             8,'() { :;}|shellshock header',                        0.10),
 ('SIG-371','T1190','NTP monlist abuse',                       'ntpd monlist query from external',                                6,'monlist|ntpd query',                                0.20),
 ('SIG-372','T1190','DNS ANY query amplification',             'ANY query from external for amp',                                 6,'dns any query|amp any',                             0.25),
 ('SIG-373','T1071.001','Fastjson RCE',                        'Fastjson known gadget',                                           9,'fastjson|@type|com.sun.rowset',                     0.15),
 ('SIG-374','T1190','Jackson RCE',                             'Jackson polymorphic deserialization',                             9,'jackson deser|@JsonTypeInfo',                       0.15),
 ('SIG-375','T1190','Apache OFBiz CVE-2023-49070',             'OFBiz groovy RCE',                                                9,'ofbiz|webtools/control/xmlrpc',                     0.10),
 ('SIG-376','T1190','JetBrains TeamCity CVE-2024-27198',       'TeamCity auth bypass',                                            9,'teamcity|CVE-2024-27198',                           0.10),
 ('SIG-377','T1190','Microsoft SmartScreen bypass',            'Mark-of-the-Web bypass',                                          7,'smartscreen bypass|MOTW bypass',                    0.20),
 ('SIG-378','T1190','Outlook CVE-2023-23397',                  'Outlook NTLM relay via reminder',                                 9,'outlook|PidLidReminderFileParameter',               0.10),
 ('SIG-379','T1190','MOVEit CVE-2024-5806',                    'MOVEit Transfer SFTP auth bypass',                                9,'moveit sftp|CVE-2024-5806',                         0.05),
 ('SIG-380','T1190','XZ backdoor CVE-2024-3094',               'XZ Utils ssh backdoor',                                          10,'xz backdoor|liblzma|CVE-2024-3094',                 0.05);

COMMIT;
